"""create models

Revision ID: 2e41194ac999
Revises:
Create Date: 2025-06-26 14:03:41.206467

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e41194ac999"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "csgo_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("price", sa.NUMERIC(precision=12, scale=2), nullable=True),
        sa.Column(
            "quality",
            sa.Enum("BS", "WW", "FT", "MW", "FN", name="quality"),
            nullable=False,
        ),
        sa.Column("currency", sa.Enum("USD", "RUB", name="currency"), nullable=True),
        sa.Column("float_value", sa.NUMERIC(precision=18, scale=16), nullable=True),
        sa.Column("pattern", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "custom_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items_on_sale",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("csgo_item_id", sa.Integer(), nullable=True),
        sa.Column("custom_item_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "game_type",
            sa.Enum("DOTA", "CS2", "TF2", "RUST", "CSGO", name="gametype"),
            nullable=False,
        ),
        sa.Column("purchase_price", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column("selling_price", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column(
            "source_marketplace",
            sa.Enum(
                "STEAM", "TM", "CSMONEY", "LOOTFARM", "TRADEIT", name="marketplace"
            ),
            nullable=False,
        ),
        sa.Column(
            "target_marketplace",
            sa.Enum(
                "STEAM", "TM", "CSMONEY", "LOOTFARM", "TRADEIT", name="marketplace"
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.Enum("USD", "RUB", name="currency"), nullable=True),
        sa.Column("is_sold", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["csgo_item_id"],
            ["csgo_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["custom_item_id"],
            ["custom_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items_on_sale")
    op.drop_table("custom_items")
    op.drop_table("csgo_items")
    # ### end Alembic commands ###
