"""Create table models

Revision ID: 3a4bd048a7c6
Revises: f941f873a078
Create Date: 2025-06-25 15:24:12.982115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4bd048a7c6'
down_revision: Union[str, Sequence[str], None] = 'f941f873a078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csgo_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('quality', sa.Enum('BATTLE_SCARRED', 'WELL_WORN', 'FIELD_TESTED', 'MINIMAL_WEAR', 'FACTORY_NEW', name='quality'), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'RUB', name='currency'), nullable=True),
    sa.Column('float_value', sa.NUMERIC(precision=2, scale=16), nullable=True),
    sa.Column('pattern', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_on_sale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('csgo_item_id', sa.Integer(), nullable=True),
    sa.Column('custom_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.Enum('DOTA', 'CS2', 'TF2', 'RUST', 'CSGO', name='gametype'), nullable=False),
    sa.Column('purchase_price', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('source_marketplace', sa.Enum('STEAM', 'TM', 'CSMONEY', 'LOOTFARM', 'TRADEIT', name='marketplace'), nullable=False),
    sa.Column('target_marketplace', sa.Enum('STEAM', 'TM', 'CSMONEY', 'LOOTFARM', 'TRADEIT', name='marketplace'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['csgo_item_id'], ['csgo_items.id'], ),
    sa.ForeignKeyConstraint(['custom_item_id'], ['custom_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.drop_table('items_on_sale')
    op.drop_table('custom_items')
    op.drop_table('csgo_items')
    # ### end Alembic commands ###
