"""add flag, CASCADE

Revision ID: f5c7cc60d116
Revises: 2e41194ac999
Create Date: 2025-06-30 11:53:47.164728

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5c7cc60d116"
down_revision: Union[str, Sequence[str], None] = "2e41194ac999"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("csgo_items", sa.Column("is_void", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.drop_constraint(
        "items_on_sale_csgo_item_id_fkey", "items_on_sale", type_="foreignkey"
    )
    op.drop_constraint(
        "items_on_sale_custom_item_id_fkey", "items_on_sale", type_="foreignkey"
    )

    op.create_foreign_key(
        "items_on_sale_csgo_item_id_fkey",
        "items_on_sale",
        "csgo_items",
        ["csgo_item_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.create_foreign_key(
        "items_on_sale_custom_item_id_fkey",
        "items_on_sale",
        "custom_items",
        ["custom_item_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("csgo_items", "is_void")
    # ### end Alembic commands ###

    op.drop_constraint("items_on_sale_csgo_item_id_fkey", "items_on_sale")
    op.drop_constraint("items_on_sale_custom_item_id_fkey", "items_on_sale")

    op.create_foreign_key(
        "items_on_sale_csgo_item_id_fkey",
        "items_on_sale",
        "csgo_items",
        ["csgo_item_id"],
        ["id"],
    )

    op.create_foreign_key(
        "items_on_sale_custom_item_id_fkey",
        "items_on_sale",
        "custom_items",
        ["custom_item_id"],
        ["id"],
    )
